### ISSUE TITLE
webextensions.api.notifications - Left column partially hidden

### ISSUE THREAD

**Issue by Pheil** [mdn/yari#4514]
Was told to submit this here.

https://github.com/mdn/browser-compat-data/issues/12063

**Comment by peterbe** [comment]
@schalkneethling @tannerdolby ?

**Comment by tannerdolby** [comment]
I read through the issue mentioned above and its been fixed in #4329. I just double checked the page https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications and there isn't any `nowrap` anywhere and the sidebar values break onto new lines when they overflow their content box.

Unless the OP can reproduce the issue, I reckon this can be closed as its already been resolved. The "Browser Support ..." text is one of the longer records in the sidebar and the video below shows on the live site that it wraps onto the next line and doesn't overflow. 


https://user-images.githubusercontent.com/48612525/130103783-61ed08ca-4e2c-4a80-a222-22f92d81f651.mov

**Comment by peterbe** [comment]
This is what it looks like on the `main` as of right now. 
<img width="774" alt="Screen Shot 2021-08-19 at 12 14 27 PM" src="https://user-images.githubusercontent.com/26739/130104603-504070c5-2614-4601-a9bb-3e678050e45c.png">

A new prod build is going out in approximately 5-6 hours.

**Comment by peterbe** [comment]
Let's wait till tomorrow and if @Pheil can re-test tomorrow, you can close it. 

Tip: The CDN cache might be still hot and stale tomorrow. To bypass that, mess with *case* of the slug. E.g. `wEBeXtensions` instead.

**Comment by tannerdolby** [comment]
> This is what it looks like on the main as of right now.

Ohh that sidebar in the BCD tables, not the sidebar next to the `<main>` content. Let me take another look. I know I resolved the BCD header cells overflowing in a previous PR. Let me investigate.

**Comment by Pheil** [comment]
Sure, I can retest tomorrow.  I should have clarified that I meant the compatibility table not sidebar

**Comment by tannerdolby** [comment]
> Sure, I can retest tomorrow. I should have clarified that I meant the compatibility table not sidebar

Perfect. And no worries, I should have read more clearly. Thanks again for bringing this to light.

**Comment by tannerdolby** [comment]
Just as I expected, this was fixed in #4241 but the PR was merged ~8hrs ago so the changes haven't hit the main site. Once they do land tomorrow, this issue should be resolved @peterbe!

**Comment by tannerdolby** [comment]
Can confirm this issue is resolved and is ready to be closed. The bcd header column values now wrap onto multiple lines when they would otherwise overflow their content-box. 

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications

<img width="1255" alt="Screen Shot 2021-08-20 at 8 03 23 AM" src="https://user-images.githubusercontent.com/48612525/130253715-502b02de-d0db-4bdd-9edf-278633674dce.png">

**Comment by Pheil** [comment]
How long should I expect to wait to see the fix live on the site?  Still looks the same to me.

**Comment by Pheil** [comment]
FYI, still showing not fixed for me.  I've hard reloaded and checked with two browsers.

**Comment by tannerdolby** [comment]
That's odd, it must be a caching issue or your not viewing the correct URL. I can confirm the page is reflecting the changes from #4241 landing and the overflow is fixed where text breaks onto the next line in Chrome, Firefox, Safari. 

Tips to reset cache:
- For mac - use `cmd` + `shift` + `r` to reset browser cache
- For Windows - use `shift` + `r` or use the option of using the menu from browser options to reset cache

**Comment by Pheil** [comment]
Didn't realize this was closed.  Not sure what the issue is getting the latest page on my end, but it's not my cache.
https://user-images.githubusercontent.com/1458226/132591893-08606fad-adcd-4906-8a3f-1f6b7b32e119.mp4

**Comment by tannerdolby** [comment]
> Didn't realize this was closed. Not sure what the issue is getting the latest page on my end, but it's not my cache.

What browser are you using, and what version?

**Comment by Pheil** [comment]
The video specifically is from Edge (93.0.961.38), I also get the same result in Firefox (92.0)

**Comment by tannerdolby** [comment]
Have you tried in Chrome?

**Comment by Pheil** [comment]
I don't have Chrome on this PC, but will test on my work's PC tomorrow.

**Comment by tannerdolby** [comment]
Ah I see. No worries, I just wanted to see if it was at least working on one browser.

**Comment by tannerdolby** [comment]
@Pheil Your right, I just looked at the page on Firefox and the changes that are visible on Chrome are not there. All along there hasn't been support for Firefox or Edge. I will pinpoint which properties aren't fully supported and hopefully submit a PR to fix this by tomorrow morning.

**Comment by tannerdolby** [comment]
Found the problem. It was `display: flex` on `.bc-table-row-header code` causing issues in Firefox. After removing that flexbox declaration it behaves the same in Firefox as in Chrome. Will check Edge now before submitting a PR to fix this.

**Comment by tannerdolby** [comment]
Recap:

- Add `-webkit-flex` vendor prefix to ensure that `display: flex` is working properly on Edge and Safari.
- Change `word-wrap: break-word` to `word-wrap: anywhere` for `.bc.table-row-header code` elements as thats what makes Firefox and Edge happy.  (https://stackoverflow.com/questions/56304531/what-does-anywhere-mean-in-word-wrap-css-property).

Also, note we won't see `hyphens: auto` in Edge or Firefox as its only supported by Chrome.

**Comment by tannerdolby** [comment]
This can be reopened and then once #4638 is reviewed/merged we can reclose this issue as it still is problematic in Edge/Firefox until 4638 lands.

cc @schalkneethling

**Comment by Pheil** [comment]
Not to make this more confusing, but I checked Chrome 93 and 95 on my work PC with the same hard reloads and it doesn't show the updated page either.  Is there a way to check the css version from the developer tools?

**Comment by schalkneethling** [comment]
> Not to make this more confusing, but I checked Chrome 93 and 95 on my work PC with the same hard reloads and it doesn't show the updated page either. Is there a way to check the css version from the developer tools?

Are you using https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications to test? If so, try using https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/Notifications and see if the result is different.

**Comment by Pheil** [comment]
I wouldn't expect the pages to be case sensitive and they are not.  Same result for both.

**Comment by tannerdolby** [comment]
The changes merged in #4638 won't take effect probably for a few more hours if not by the end of the day. I just checked Chrome and as expected its working correctly breaking to the next line. But since the changes in 4638 haven't landed on the main site yet, Firefox and presumably Edge still are waiting for those changes to land before things work as expected.

**Comment by Pheil** [comment]
@tannerdolby Fixed!  Tested Firefox, Chrome, Edge (chrome)

**Comment by tannerdolby** [comment]
Ok great! I'm glad to hear it @Pheil. Feel free to report back if you encounter any other issues. Thanks for all your help on this.
